# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .gender import Gender
from .sampling_params import SamplingParams


class Voice(UniversalBaseModel):
    id: str
    gender: typing.Optional[Gender] = None
    accent: typing.Optional[str] = None
    age: typing.Optional[str] = None
    sampling_params: typing.Optional[SamplingParams] = pydantic.Field(default=None)
    """
    Default sampling params for this voice. See also [Sampling Params Guide](../tts/sampling-params-guide).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
